### PR TITLE
Use localisable timezone to rate limit check-ins

### PR DESCRIPTION
**Pull request by jackmurdoch**
Dependant on infra changes - additional param `time_zone` is required. Will fix conflicts and merge when this has been completed.

### CODE REVIEW

**Review by colmharte — APPROVED** [review]

**Comment by dennisgove** [comment]
This only works if the entire covered region for a specific CovidGreen deployment (ie, a state in the US) is all within one timezone. That is not always the case. You can see on [this listing](https://simple.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_time_zone) that there are at least 21 states/territories with multiple timezones and/or different daylight savings rules.

**Comment by jackmurdoch** [comment]
> This only works if the entire covered region for a specific CovidGreen deployment (ie, a state in the US) is all within one timezone. That is not always the case. You can see on [this listing](https://simple.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_time_zone) that there are at least 21 states/territories with multiple timezones and/or different daylight savings rules.

Good point. Another option would be to accept a `timezone` in the request, and use that for rate limiting. It opens up some abuse, but I think the risk is minimal enough that it'd work. Thoughts? @colmharte @dennisgove 

Also, we could accept the current time from the user's device and then only accept it if it falls within an acceptable range of the server's current time?

**Comment by dennisgove** [comment]
When it comes to timezones I've found there is never a perfect answer. Accepting the user's current time doesn't quite get us what we want because (theoretically) that time would be transmitted in UTC and wouldn't tell us the user's local time. Or we send the users local time which feels like an antipattern.

In places where the user's local time is important (like scheduling systems) it becomes necessary to track/transmit the user's timezone. I think this is the only reasonable approach, even though it feels wrong.

Alternatively, we reduce the rate limit on the server to a period that is unlikely to see this issue. For example, a 2hr rate limit would make it an unlikely scenario to appear in the real world.

**Comment by jackmurdoch** [comment]
You make good points, and I think the 2 hour rate limit idea is probably the best approach. However, I'm going to prepare to merge this PR as it is for now. This solution covers all of the existing tenants, and we can make improvements if and when we need to cater for states/regions covering multiple time zones.

**Review by dennisgove — APPROVED** [review]
I agree with that assessment. Please create an issue on the repo to track this known item.

**Pull request merged**
